name: frontend
replicaCount: 3

image:
  tag: "3.1.2"

serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: k8s-sa@logical-acolyte-423107-b5.iam.gserviceaccount.com

ingress:
  host: "frontend.yanirw.com"

global:
  ingress:
    className: "gce"
    tls:
      enabled: true
      secretName: "cloudflare-tls"
