frontend:
  image:
    tag: "3.1.4"
  serviceAccount:
    annotations:
      iam.gke.io/gcp-service-account: k8s-sa@logical-acolyte-423107-b5.iam.gserviceaccount.com
  ingress:
    host: "frontend.yanirw.com"

echo_server:
  image:
    tag: "3.1.0"
  serviceAccount:
    annotations:
      iam.gke.io/gcp-service-account: k8s-sa@logical-acolyte-423107-b5.iam.gserviceaccount.com
  ingress:
    host: "echo.yanirw.com"

global:
  ingress:
    className: "gce"
    tls:
      enabled: true
      secretName: "cloudflare-tls"